[book]
title = "QuinusLang"
authors = []
description = "Systems programming language with assembly-level control"
src = "docs"
language = "en"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
site-url = "https://ryannzander.github.io/QuinusLang/"
git-repository-url = "https://github.com/ryannzander/QuinusLang"
git-repository-icon = "fab-github"
edit-url-template = "https://github.com/ryannzander/QuinusLang/edit/master/{path}"
no-section-label = true
