//! Parse and write qpp.lock

use crate::error::{Error, Result};
use std::collections::HashMap;
use std::path::Path;

#[derive(Debug, Clone, Default)]
pub struct Lockfile {
    pub packages: HashMap<String, LockedPackage>,
}

#[derive(Debug, Clone)]
pub struct LockedPackage {
    pub version: String,
    pub source: String,
}

pub fn parse_lockfile(path: &Path) -> Result<Lockfile> {
    if !path.exists() {
        return Ok(Lockfile::default());
    }
    let content = std::fs::read_to_string(path).map_err(|e| Error::Package {
        message: format!("Failed to read lockfile: {}", e),
    })?;

    let mut lockfile = Lockfile::default();
    let mut current = None;

    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line.starts_with("[[package]]") {
            current = Some(String::new());
            continue;
        }
        if let Some((key, value)) = line.split_once('=') {
            let key = key.trim().trim_matches('"');
            let value = value.trim().trim_matches('"');
            if key == "name" {
                if let Some(ref mut c) = current {
                    *c = value.to_string();
                }
            } else if key == "version" {
                if let Some(ref name) = current {
                    lockfile.packages.insert(
                        name.clone(),
                        LockedPackage {
                            version: value.to_string(),
                            source: "registry".to_string(),
                        },
                    );
                }
            }
        }
    }

    Ok(lockfile)
}

pub fn write_lockfile(path: &Path, lockfile: &Lockfile) -> Result<()> {
    let mut content = String::from("# This file is automatically generated\n\n");
    for (name, pkg) in &lockfile.packages {
        content.push_str("[[package]]\n");
        content.push_str(&format!("name = \"{}\"\n", name));
        content.push_str(&format!("version = \"{}\"\n", pkg.version));
        content.push_str(&format!("source = \"{}\"\n\n", pkg.source));
    }
    std::fs::write(path, content).map_err(|e| Error::Package {
        message: format!("Failed to write lockfile: {}", e),
    })?;
    Ok(())
}
