name: Deploy docs

on:
  push:
    branches: [main, master]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install MkDocs and QuinusLang lexer
        run: |
          pip install mkdocs-material
          pip install ./pygments_quinus

      - name: Deploy
        run: mkdocs gh-deploy --force
